name: PCFly
main: Angel\PCFly\Main
api: 3.0.0
version: 4.0.0
author: Angel
commands:
  fly:
    description: "Fly in survival mode"
    permission: fly.command
permissions:
  fly.command:
    default: op
